from datetime import datetime

from RPA.Robocorp.utils import get_output_dir


# Various user-defined constants:
TODAY = datetime.strftime(datetime.now(), "%Y-%m-%d")
# File which gets attached in the output Work Items produced by the Producer. This file
#  is generated by a pre-run script configured in the robot.yaml.
WORKITEM_FILE_PATH = str(get_output_dir() / "random-workitem-file.txt")
